<a href="https://colab.research.google.com/github/GuillaumeArp/Wild_Notebooks/blob/main/ML_Challenge_Classification_KNN_distances_with_Pokemons_Guillaume_Arp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [ ]:
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/murpi/wilddata/master/pokemon.csv', sep=',', index_col=0)
df.head()

            Name Type 1  Type 2  HP  ...  Sp. Def  Speed  Generation  Legendary
#                                    ...
1      Bulbasaur  Grass  Poison  45  ...       65     45           1      False
2        Ivysaur  Grass  Poison  60  ...       80     60           1      False
3       Venusaur  Grass  Poison  80  ...      100     80           1      False
4  Mega Venusaur  Grass  Poison  80  ...      120     80           1      False
5     Charmander   Fire     NaN  39  ...       50     65           1      False

[5 rows x 11 columns]

## Preprocessing

In [ ]:
df = pd.get_dummies(data=df, columns=['Type 1', 'Type 2'])
df

               Name  HP  Attack  ...  Type 2_Rock  Type 2_Steel  Type 2_Water
#                                ...
1         Bulbasaur  45      49  ...            0             0             0
2           Ivysaur  60      62  ...            0             0             0
3          Venusaur  80      82  ...            0             0             0
4     Mega Venusaur  80     100  ...            0             0             0
5        Charmander  39      52  ...            0             0             0
..              ...  ..     ...  ...          ...           ...           ...
796         Diancie  50     100  ...            0             0             0
797    Mega Diancie  50     160  ...            0             0             0
798  Hoopa Confined  80     110  ...            0             0             0
799   Hoopa Unbound  80     160  ...            0             0             0
800       Volcanion  80     110  ...            0             0             1

[800 rows x 45 columns]

In [ ]:
deck_names = ['Mewtwo', 'Lugia', 'Rayquaza', 'Giratina Origin Forme', 'Dialga', 'Palkia']
df_deck = df[df['Name'].isin(deck_names)]
df_deck

                      Name   HP  ...  Type 2_Steel  Type 2_Water
#                                ...
163                 Mewtwo  106  ...             0             0
270                  Lugia  106  ...             0             0
426               Rayquaza  105  ...             0             0
541                 Dialga  100  ...             0             0
542                 Palkia   90  ...             0             0
546  Giratina Origin Forme  150  ...             0             0

[6 rows x 45 columns]

In [ ]:
df_not_legendary = df.loc[df['Legendary'] == False]
df_not_legendary

                     Name  HP  Attack  ...  Type 2_Rock  Type 2_Steel  Type 2_Water
#                                      ...
1               Bulbasaur  45      49  ...            0             0             0
2                 Ivysaur  60      62  ...            0             0             0
3                Venusaur  80      82  ...            0             0             0
4           Mega Venusaur  80     100  ...            0             0             0
5              Charmander  39      52  ...            0             0             0
..                    ...  ..     ...  ...          ...           ...           ...
788  Gourgeist Super Size  85     100  ...            0             0             0
789              Bergmite  55      69  ...            0             0             0
790               Avalugg  95     117  ...            0             0             0
791                Noibat  40      30  ...            0             0             0
792               Noivern  85      70  ...            0             0             0

[735 rows x 45 columns]

In [ ]:
cols = df_not_legendary.columns.tolist()
del cols[7:9]
del cols[0]

In [ ]:
cols

['HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Type 1_Bug',
 'Type 1_Dark',
 'Type 1_Dragon',
 'Type 1_Electric',
 'Type 1_Fairy',
 'Type 1_Fighting',
 'Type 1_Fire',
 'Type 1_Flying',
 'Type 1_Ghost',
 'Type 1_Grass',
 'Type 1_Ground',
 'Type 1_Ice',
 'Type 1_Normal',
 'Type 1_Poison',
 'Type 1_Psychic',
 'Type 1_Rock',
 'Type 1_Steel',
 'Type 1_Water',
 'Type 2_Bug',
 'Type 2_Dark',
 'Type 2_Dragon',
 'Type 2_Electric',
 'Type 2_Fairy',
 'Type 2_Fighting',
 'Type 2_Fire',
 'Type 2_Flying',
 'Type 2_Ghost',
 'Type 2_Grass',
 'Type 2_Ground',
 'Type 2_Ice',
 'Type 2_Normal',
 'Type 2_Poison',
 'Type 2_Psychic',
 'Type 2_Rock',
 'Type 2_Steel',
 'Type 2_Water']

In [ ]:
df_not_legendary[cols].head()

   HP  Attack  Defense  ...  Type 2_Rock  Type 2_Steel  Type 2_Water
#                       ...
1  45      49       49  ...            0             0             0
2  60      62       63  ...            0             0             0
3  80      82       83  ...            0             0             0
4  80     100      123  ...            0             0             0
5  39      52       43  ...            0             0             0

[5 rows x 42 columns]

## Model

In [ ]:
X = df_not_legendary[cols]

distanceKNN = NearestNeighbors(n_neighbors=1).fit(X)
distanceKNN

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                 radius=1.0)

In [ ]:
pokemon_list = distanceKNN.kneighbors(df_deck[cols].values)
pokemon_list

(array([[42.24926035],
        [46.07602413],
        [36.79673899],
        [36.4280112 ],
        [31.52776554],
        [58.33523806]]), array([[242],
        [508],
        [268],
        [ 12],
        [  8],
        [159]]))

In [ ]:
items = pokemon_list[1].reshape(1,6)[0]
items

array([242, 508, 268,  12,   8, 159])

In [ ]:
df_new_deck = df_not_legendary.iloc[items]
df_new_deck

                 Name   HP  Attack  ...  Type 2_Rock  Type 2_Steel  Type 2_Water
#                                   ...
249     Mega Houndoom   75      90  ...            0             0             0
547         Cresselia  120      70  ...            0             0             0
280     Mega Blaziken   80     160  ...            0             0             0
13     Mega Blastoise   79     103  ...            0             0             0
9    Mega Charizard Y   78     104  ...            0             0             0
166               Mew  100     100  ...            0             0             0

[6 rows x 45 columns]

In [ ]:
def undummify(df, prefix_sep="_"):
    cols2collapse = {
        item.split(prefix_sep)[0]: (prefix_sep in item) for item in df.columns
    }
    series_list = []
    for col, needs_to_collapse in cols2collapse.items():
        if needs_to_collapse:
            undummified = (
                df.filter(like=col)
                .idxmax(axis=1)
                .apply(lambda x: x.split(prefix_sep, maxsplit=1)[1])
                .rename(col)
            )
            series_list.append(undummified)
        else:
            series_list.append(df[col])
    undummified_df = pd.concat(series_list, axis=1)
    return undummified_df

## Final Result

In [ ]:
df_new_deck = undummify(df_new_deck)
df_new_deck = df_new_deck[['Name','Type 1','Type 2','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed','Generation','Legendary']]
df_new_deck

                 Name   Type 1    Type 2  ...  Speed  Generation  Legendary
#                                         ...
249     Mega Houndoom     Dark      Fire  ...    115           2      False
547         Cresselia  Psychic       Bug  ...     85           4      False
280     Mega Blaziken     Fire  Fighting  ...    100           3      False
13     Mega Blastoise    Water       Bug  ...     78           1      False
9    Mega Charizard Y     Fire    Flying  ...    100           1      False
166               Mew  Psychic       Bug  ...    100           1      False

[6 rows x 11 columns]

This is the closest deck to his legendary one, taking into account stats and types.